### ISSUE TITLE
Unsupported Overhang Holes

### ISSUE THREAD

**Issue by Alexander-T-Moss** [kejar31/VoronMods#2]
Firstly, I'm loving this project, and am really excited to get it installed sooner than later :) But I think the printability of the models can be improved by adding built in bridging support on the overhanging holes ( see photo attached )

<img width="398" alt="image" src="https://user-images.githubusercontent.com/54496326/180397311-6c2009fd-b622-4e82-bc67-3b141c19ffaa.png">

**Comment by kejar31** [comment]
Maybe… I will consider it but have not really had an issue on the two holes this effects myself

**Comment by kejar31** [comment]
I fixed this on the latest release. closing
