### ISSUE TITLE
Gland M12

### ISSUE THREAD

**Issue by RickDnamps** [kejar31/VoronMods#3]
I don't know if it just me but my Gland  M12 is not working

I try ti use this part: https://www.amazon.ca/gp/product/B07R7759BW/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

There is not enough place to screw the second part which support the cable.

Do you think it's possible to know what is your part number or where you get it.

Thx

Edit:

Just saw your part on DFH ... I will try to see what is the difference with my part.

**Comment by kejar31** [comment]
This was tested and built around the ones from DFH which at their widest point are 18mm. Sorry I can’t buy every gland and test … I do plan on releasing a new version that will include a gland (minus strain relief)
