### ISSUE TITLE
Not working with motor 36STH20 

### ISSUE THREAD

**Issue by RickDnamps** [kejar31/VoronMods#4]
This MOD is not working with the motor 36STH20.

This concept is done arround all standard part (I think, maybe I'm wrong). If you have some mod example Stealth Burner GALILEO extruder with 36STH20 that mod won't work.

I'm not saying that to complain, but more for information for other people. I think this support is very nice looking and the guys who develop it done a good job.

**Comment by kejar31** [comment]
I am confused, are you saying it won’t work with this motor? If so why not? Or are you saying this won’t work with Galileo?

**Comment by RickDnamps** [comment]
The space is not enough to clear the 36STH20 ... Which motor you have ?
The Standard motor is 36STH17

**Comment by RickDnamps** [comment]
![IMG20220802213840](https://user-images.githubusercontent.com/103229273/182505777-d001b725-ab9c-4c29-b447-10a6fcc93a6d.jpg)
![IMG20220802213805](https://user-images.githubusercontent.com/103229273/182505780-1ea78668-f5d0-4c46-852f-6a16722e129c.jpg)

**Comment by kejar31** [comment]
Wait.. there is plenty of room for the motor so long as you use CW2 and not Galileo... I mean I say this is for CW2 right in the name

**Comment by RickDnamps** [comment]
OK Sorry Kejar31, you right with the Clockwork2 without the galileo spacer you should be OK! !! 
So for The Galileo forget that guys !!

**Comment by kejar31** [comment]
Well the cad is right there… if you want it for something else you are free to take it and do what you need.
