### ISSUE TITLE
Can't Get Connector Through Cable Gland Mount

### ISSUE THREAD

**Issue by Alexander-T-Moss** [kejar31/VoronMods#7]
I don't know if this is a "me" issue but when I was installing my CB-C2 I had to cut the molex connector off one end of the harness I was using to get it through the cable gland mount as the 4 pin molex connector for the EBB36 won't go through the cable gland mount. So would it be possible to modify the mount to have a cutout in the side of it so once I unscrew the cable gland, the harness will slide in and out through the side? ( I played around in CAD and will test it out when I reprint the parts in PCCF )

[Modified Cable Gland.zip](https://github.com/kejar31/VoronMods/files/9336785/Modified.Parts.zip)

<img width="582" alt="image" src="https://user-images.githubusercontent.com/54496326/184623083-bb01d122-19f1-497a-ac56-0ce60d06e876.png">

**Comment by kejar31** [comment]
Humm this isn’t a bad idea… I will test this out later and may implement it.. will def give you credit etc

**Comment by Alexander-T-Moss** [comment]
As a quick bodge I just cut a section out of the original one I had installed and there doesn't seem to be any issue with it. Unfortunately I'll not be able to test out printing it with the cutout as I'm now away from my printer for two weeks :)

**Comment by Alexander-T-Moss** [comment]
Having tested the alternate cable gland mount I can verify it works without issue :)
![0824F080-30E3-49E3-8AAD-CB8388397FDA](https://user-images.githubusercontent.com/54496326/188268424-69b263a4-975a-48ad-a667-fc44639076c3.jpeg)

**Comment by kejar31** [comment]
As I am looking to do and upgrade to this project.. I am going to give this a good look.. if used you will have solved an annoying issue. Thank you sir!

**Comment by Alexander-T-Moss** [comment]
No problem 🙂

**Comment by kejar31** [comment]
I did end up using this, thank you again good sir
