### ISSUE TITLE
[CB-C2] Gland Size

### ISSUE THREAD

**Issue by whi-tw** [kejar31/VoronMods#8]
I've been trying to locate a M12 gland with strain relief (not in US, so DFH isn't all that useful), and have been having trouble finding one - M12 glands seem to be M12 on one side, and M16 on the other.

https://github.com/kejar31/VoronMods/issues/6#issuecomment-1207303850 refers to PG7, which makes a lot more sense, as the PG-threaded glands seem to have the same thread on each side.

Can you please confirm if PG7 is actually the correct size, and if so, could this be added to the BOM?

**Comment by whi-tw** [comment]
Just spotted #3. Seems to be the same issue I had with https://www.amazon.co.uk/gp/product/B07QHSRB45.

I have just started a return, and have ordered https://www.amazon.co.uk/gp/product/B07QPXF3WC, and will update when I receive it on Thursday.

It might be that it 'fits', but the pitch isn't correct (if you modelled it for M12 specifically). If so, it could be worth making a PG7 variant of the part?

**Comment by kejar31** [comment]
You need to make sure that the gland is never had a larger circumference than 18mm

**Comment by whi-tw** [comment]
@kejar31 for sure, fully understand that. The potential problem I'm seeing is that if the thread pitch is modeled for M12, it won't necessarily mesh correctly with the PG7 thread. A comparison of the thread pitches [is here](https://mencom.com/infographics/Cable-Gland-Threads-Comparison.pdf).

Specifically, the dimensions are different (all in mm, taken from the linked PDF):

| Thread | Major Diameter | Pitch | Through Hole | Flank Angle |
| ------ | -------------- | ----- | ------------ | ----------- |
| M12    | 12             | 1.5   | 12.5         | 60°         |
| PG7    | 12.5           | 1.27  | 12.7         | 80°         |

**Comment by kejar31** [comment]
Ahh that can easily be fixed in onshape…

**Comment by whi-tw** [comment]
~~Seems this was a non-issue. PG7 fits A-OK in the existing thread.~~

Nope, is definitely bending the threads on my glands, as the pitch is 0.25mm too large. printing out some test threads as I have a gland with each thread size, and once they're done, I'll update you.

**Comment by whi-tw** [comment]
I've made [a test part in Onshape](https://cad.onshape.com/documents/024c7f542f5bf9c0c1133d19/w/99e2428d6a55f5207931fce5/e/6c30153d0c7476fda1efc462), and have made the two possible threads.

Can confirm that the two glands I have are PG7 (the one that fits in the space in CB-C2) and MG12x1.5 (the one that is too girthy to fit properly).

**Comment by whi-tw** [comment]
PG7-threaded part is [in this doc](https://cad.onshape.com/documents/10a4b08bf39b40b13f7e0b3b/w/03e87fb5e724d9d7011ed651/e/ac55cbcf553b9b071bcf298b). Untested, but presumably it'll work, as it's got the same thread characteristics as my test part.

**Comment by whi-tw** [comment]
Confirmed, fits perfectly.
