### ISSUE TITLE
20mm fan

### ISSUE THREAD

**Issue by marsb007** [kejar31/VoronMods#9]
The Sunon 20mm fan is extremely loud and annoying. Frankly to the point of being unusable. I've also found it hard to get it to work on the probe pins. It works on 5v + GND (always on) but when I move it to 5v + PB9 and configure in klipper, it won't turn on. I essentially can't turn it down at all.

I see that the space is rather tight where the fan currently is, but you could fit a 30mm fan (also easier to source and probably quiter) on the opposite side door/cover (where the Hartk PCB would normally be and where the SB2040 is).

**Comment by kejar31** [comment]
Idk mine is not that loud… I personally run mine on a 5v and have the ground shared with the hotend fan… this allows for it to shut off when the printer is not in use Sent from my iPhoneOn Dec 4, 2022, at 8:48 AM, marsb007 ***@***.***> wrote:﻿
The Sunon 20mm fan is extremely loud and annoying. Frankly to the point of being unusable. I've also found it hard to get it to work on the probe pins. It works on 5v + GND (always on) but when I move it to 5v + PB9 and configure in klipper, it won't turn on. I essentially can't turn it down at all.
I see that the space is rather tight where the fan currently is, but you could fit a 30mm fan (also easier to source and probably quiter) on the opposite side door/cover (where the Hartk PCB would normally be and where the SB2040 is).

**Comment by morph5555** [comment]
@marsb007 

https://github.com/HyperToxic33/EBB-Fan-Control

**Comment by kejar31** [comment]
yes I have seen that mod but again I am not having any issues with noise on my fan its actually quieter than my hot end fan... Then considering that I am just sharing the ground with my hotend fan its not running unless its printing and like I said the hotend fan is louder.. You may have a knock-off maglev IDK... closing this issue
